"""Add web projects tables for Studio Web IA

Revision ID: da404cf7fa6d
Revises: 
Create Date: 2025-11-22 16:17:20.138011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da404cf7fa6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('niche', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('face_image_url', sa.Text(), nullable=True),
    sa.Column('face_embedding', sa.JSON(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('tone_of_voice', sa.String(length=50), nullable=True),
    sa.Column('generation_settings', sa.JSON(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_influencers_created_at'), 'ai_influencers', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_influencers_id'), 'ai_influencers', ['id'], unique=False)
    op.create_index(op.f('ix_ai_influencers_user_id'), 'ai_influencers', ['user_id'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('featured_image', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_image', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_created_at'), 'blog_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_index(op.f('ix_blog_posts_website_id'), 'blog_posts', ['website_id'], unique=False)
    op.create_table('catalog_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_favorites_id'), 'catalog_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_favorites_user_id'), 'catalog_favorites', ['user_id'], unique=False)
    op.create_table('ebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('chapters', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('audience', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('has_cover', sa.Boolean(), nullable=True),
    sa.Column('has_toc', sa.Boolean(), nullable=True),
    sa.Column('has_illustrations', sa.Boolean(), nullable=True),
    sa.Column('has_summaries', sa.Boolean(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('epub_url', sa.String(length=500), nullable=True),
    sa.Column('mobi_url', sa.String(length=500), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('table_of_contents', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebooks_created_at'), 'ebooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_ebooks_id'), 'ebooks', ['id'], unique=False)
    op.create_index(op.f('ix_ebooks_user_id'), 'ebooks', ['user_id'], unique=False)
    op.create_table('email_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('preview_text', sa.String(length=255), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('clicked_count', sa.Integer(), nullable=True),
    sa.Column('bounced_count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_campaigns_created_at'), 'email_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_campaigns_id'), 'email_campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_email_campaigns_user_id'), 'email_campaigns', ['user_id'], unique=False)
    op.create_table('funnel_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=100), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=True),
    sa.Column('exits', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_time_spent', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_analytics_date'), 'funnel_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_funnel_analytics_funnel_id'), 'funnel_analytics', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_funnel_analytics_id'), 'funnel_analytics', ['id'], unique=False)
    op.create_table('funnel_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('completed_steps', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('has_converted', sa.Boolean(), nullable=True),
    sa.Column('conversion_value', sa.Float(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('total_emails_opened', sa.Integer(), nullable=True),
    sa.Column('total_emails_clicked', sa.Integer(), nullable=True),
    sa.Column('total_pages_viewed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_contacts_created_at'), 'funnel_contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_funnel_contacts_email'), 'funnel_contacts', ['email'], unique=False)
    op.create_index(op.f('ix_funnel_contacts_funnel_id'), 'funnel_contacts', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_funnel_contacts_id'), 'funnel_contacts', ['id'], unique=False)
    op.create_table('funnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('automations', sa.JSON(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('avg_time_to_convert', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnels_created_at'), 'funnels', ['created_at'], unique=False)
    op.create_index(op.f('ix_funnels_id'), 'funnels', ['id'], unique=False)
    op.create_index(op.f('ix_funnels_user_id'), 'funnels', ['user_id'], unique=False)
    op.create_table('generated_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('product_image_url', sa.String(length=500), nullable=False),
    sa.Column('ad_type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('voice', sa.String(length=50), nullable=False),
    sa.Column('cta', sa.String(length=255), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_ads_created_at'), 'generated_ads', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_ads_id'), 'generated_ads', ['id'], unique=False)
    op.create_index(op.f('ix_generated_ads_user_id'), 'generated_ads', ['user_id'], unique=False)
    op.create_table('generated_audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('audio_type', sa.String(length=50), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_audio_created_at'), 'generated_audio', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_audio_id'), 'generated_audio', ['id'], unique=False)
    op.create_index(op.f('ix_generated_audio_user_id'), 'generated_audio', ['user_id'], unique=False)
    op.create_table('generated_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_created_at'), 'generated_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_images_id'), 'generated_images', ['id'], unique=False)
    op.create_index(op.f('ix_generated_images_user_id'), 'generated_images', ['user_id'], unique=False)
    op.create_table('generated_logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('symbols', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('variations', sa.JSON(), nullable=True),
    sa.Column('selected_variation', sa.Integer(), nullable=True),
    sa.Column('logo_main_url', sa.Text(), nullable=True),
    sa.Column('logo_horizontal_url', sa.Text(), nullable=True),
    sa.Column('logo_vertical_url', sa.Text(), nullable=True),
    sa.Column('logo_icon_url', sa.Text(), nullable=True),
    sa.Column('favicon_url', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_logos_created_at'), 'generated_logos', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_logos_id'), 'generated_logos', ['id'], unique=False)
    op.create_index(op.f('ix_generated_logos_user_id'), 'generated_logos', ['user_id'], unique=False)
    op.create_table('generated_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_videos_created_at'), 'generated_videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_videos_id'), 'generated_videos', ['id'], unique=False)
    op.create_index(op.f('ix_generated_videos_user_id'), 'generated_videos', ['user_id'], unique=False)
    op.create_table('influencer_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generated_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('pose', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('outfit', sa.String(length=100), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_content_created_at'), 'influencer_content', ['created_at'], unique=False)
    op.create_index(op.f('ix_influencer_content_id'), 'influencer_content', ['id'], unique=False)
    op.create_index(op.f('ix_influencer_content_influencer_id'), 'influencer_content', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_influencer_content_user_id'), 'influencer_content', ['user_id'], unique=False)
    op.create_table('landing_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.JSON(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_landing_pages_created_at'), 'landing_pages', ['created_at'], unique=False)
    op.create_index(op.f('ix_landing_pages_id'), 'landing_pages', ['id'], unique=False)
    op.create_index(op.f('ix_landing_pages_user_id'), 'landing_pages', ['user_id'], unique=False)
    op.create_table('post_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_analytics_id'), 'post_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_post_analytics_post_id'), 'post_analytics', ['post_id'], unique=False)
    op.create_table('presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('num_slides', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('slides', sa.JSON(), nullable=True),
    sa.Column('generated_images', sa.JSON(), nullable=True),
    sa.Column('pptx_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentations_created_at'), 'presentations', ['created_at'], unique=False)
    op.create_index(op.f('ix_presentations_id'), 'presentations', ['id'], unique=False)
    op.create_index(op.f('ix_presentations_user_id'), 'presentations', ['user_id'], unique=False)
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('platform_post_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_created_at'), 'scheduled_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_id'), 'scheduled_posts', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_scheduled_time'), 'scheduled_posts', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_user_id'), 'scheduled_posts', ['user_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_created_at'), 'social_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('api_keys', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('video_shorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('voice', sa.String(length=50), nullable=True),
    sa.Column('has_music', sa.Boolean(), nullable=True),
    sa.Column('has_subtitles', sa.Boolean(), nullable=True),
    sa.Column('has_logo', sa.Boolean(), nullable=True),
    sa.Column('has_hook', sa.Boolean(), nullable=True),
    sa.Column('has_cta', sa.Boolean(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('visuals', sa.JSON(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('music_url', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_shorts_created_at'), 'video_shorts', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_shorts_id'), 'video_shorts', ['id'], unique=False)
    op.create_index(op.f('ix_video_shorts_user_id'), 'video_shorts', ['user_id'], unique=False)
    op.create_table('website_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('unique_visitors', sa.Integer(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('avg_time_on_site', sa.Integer(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('top_pages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_analytics_date'), 'website_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_website_analytics_id'), 'website_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_website_analytics_website_id'), 'website_analytics', ['website_id'], unique=False)
    op.create_table('website_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_pages_id'), 'website_pages', ['id'], unique=False)
    op.create_index(op.f('ix_website_pages_website_id'), 'website_pages', ['website_id'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('site_type', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=True),
    sa.Column('fonts', sa.JSON(), nullable=True),
    sa.Column('pages', sa.JSON(), nullable=True),
    sa.Column('menu', sa.JSON(), nullable=True),
    sa.Column('footer', sa.JSON(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.JSON(), nullable=True),
    sa.Column('favicon_url', sa.Text(), nullable=True),
    sa.Column('has_blog', sa.Boolean(), nullable=True),
    sa.Column('has_ecommerce', sa.Boolean(), nullable=True),
    sa.Column('has_contact_form', sa.Boolean(), nullable=True),
    sa.Column('has_chatbot', sa.Boolean(), nullable=True),
    sa.Column('has_analytics', sa.Boolean(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('total_page_views', sa.Integer(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index(op.f('ix_websites_created_at'), 'websites', ['created_at'], unique=False)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_user_id'), 'websites', ['user_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_created_at'), 'workflow_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_id'), 'workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_user_id'), 'workflow_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_created_at'), 'workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('project_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('git_repo_url', sa.String(length=500), nullable=True),
    sa.Column('zip_url', sa.String(length=500), nullable=True),
    sa.Column('files_structure', sa.JSON(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_project_templates_id'), 'project_templates', ['id'], unique=False)
    op.create_table('web_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('framework_version', sa.String(length=20), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('storage_type', sa.String(length=20), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('git_provider', sa.String(length=20), nullable=True),
    sa.Column('git_repo_url', sa.String(length=500), nullable=True),
    sa.Column('git_branch', sa.String(length=100), nullable=True),
    sa.Column('git_token', sa.String(length=500), nullable=True),
    sa.Column('git_username', sa.String(length=200), nullable=True),
    sa.Column('git_email', sa.String(length=200), nullable=True),
    sa.Column('deployment_provider', sa.String(length=50), nullable=True),
    sa.Column('deployment_config', sa.JSON(), nullable=True),
    sa.Column('prod_url', sa.String(length=500), nullable=True),
    sa.Column('staging_url', sa.String(length=500), nullable=True),
    sa.Column('dev_url', sa.String(length=500), nullable=True),
    sa.Column('auto_deploy', sa.Boolean(), nullable=True),
    sa.Column('auto_deploy_branch', sa.String(length=100), nullable=True),
    sa.Column('environment_vars', sa.JSON(), nullable=True),
    sa.Column('build_command', sa.String(length=500), nullable=True),
    sa.Column('start_command', sa.String(length=500), nullable=True),
    sa.Column('install_command', sa.String(length=500), nullable=True),
    sa.Column('output_directory', sa.String(length=200), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.Column('last_build_at', sa.DateTime(), nullable=True),
    sa.Column('last_deploy_at', sa.DateTime(), nullable=True),
    sa.Column('last_commit_at', sa.DateTime(), nullable=True),
    sa.Column('deploy_count', sa.Integer(), nullable=True),
    sa.Column('domain_custom', sa.String(length=200), nullable=True),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=True),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_projects_id'), 'web_projects', ['id'], unique=False)
    op.create_index(op.f('ix_web_projects_slug'), 'web_projects', ['slug'], unique=True)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('deployment_id', sa.String(length=200), nullable=True),
    sa.Column('deployment_url', sa.String(length=500), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('build_status', sa.String(length=20), nullable=True),
    sa.Column('build_logs', sa.Text(), nullable=True),
    sa.Column('build_duration', sa.Integer(), nullable=True),
    sa.Column('build_error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_rollback', sa.Boolean(), nullable=True),
    sa.Column('rollback_from_id', sa.Integer(), nullable=True),
    sa.Column('environment_vars', sa.JSON(), nullable=True),
    sa.Column('build_command', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['web_projects.id'], ),
    sa.ForeignKeyConstraint(['rollback_from_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_responses', sa.JSON(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('project_ai_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('plan_approved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('files_created', sa.JSON(), nullable=True),
    sa.Column('files_modified', sa.JSON(), nullable=True),
    sa.Column('files_deleted', sa.JSON(), nullable=True),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['web_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_ai_actions_id'), 'project_ai_actions', ['id'], unique=False)
    op.create_index(op.f('ix_project_ai_actions_project_id'), 'project_ai_actions', ['project_id'], unique=False)
    op.create_table('project_commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('author_email', sa.String(length=200), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('changed_files', sa.JSON(), nullable=True),
    sa.Column('is_merge', sa.Boolean(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('parent_hashes', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['web_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_commits_commit_hash'), 'project_commits', ['commit_hash'], unique=True)
    op.create_index(op.f('ix_project_commits_id'), 'project_commits', ['id'], unique=False)
    op.create_index(op.f('ix_project_commits_project_id'), 'project_commits', ['project_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('directory', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('lines', sa.Integer(), nullable=True),
    sa.Column('is_binary', sa.Boolean(), nullable=True),
    sa.Column('is_directory', sa.Boolean(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('encoding', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('git_status', sa.String(length=20), nullable=True),
    sa.Column('last_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('last_commit_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['web_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_id'), 'project_files', ['id'], unique=False)
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_project_commits_project_id'), table_name='project_commits')
    op.drop_index(op.f('ix_project_commits_id'), table_name='project_commits')
    op.drop_index(op.f('ix_project_commits_commit_hash'), table_name='project_commits')
    op.drop_table('project_commits')
    op.drop_index(op.f('ix_project_ai_actions_project_id'), table_name='project_ai_actions')
    op.drop_index(op.f('ix_project_ai_actions_id'), table_name='project_ai_actions')
    op.drop_table('project_ai_actions')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_web_projects_slug'), table_name='web_projects')
    op.drop_index(op.f('ix_web_projects_id'), table_name='web_projects')
    op.drop_table('web_projects')
    op.drop_index(op.f('ix_project_templates_id'), table_name='project_templates')
    op.drop_table('project_templates')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_created_at'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_user_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_created_at'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_websites_user_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_created_at'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_website_pages_website_id'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_id'), table_name='website_pages')
    op.drop_table('website_pages')
    op.drop_index(op.f('ix_website_analytics_website_id'), table_name='website_analytics')
    op.drop_index(op.f('ix_website_analytics_id'), table_name='website_analytics')
    op.drop_index(op.f('ix_website_analytics_date'), table_name='website_analytics')
    op.drop_table('website_analytics')
    op.drop_index(op.f('ix_video_shorts_user_id'), table_name='video_shorts')
    op.drop_index(op.f('ix_video_shorts_id'), table_name='video_shorts')
    op.drop_index(op.f('ix_video_shorts_created_at'), table_name='video_shorts')
    op.drop_table('video_shorts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_created_at'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_scheduled_posts_user_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_scheduled_time'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_created_at'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index(op.f('ix_presentations_user_id'), table_name='presentations')
    op.drop_index(op.f('ix_presentations_id'), table_name='presentations')
    op.drop_index(op.f('ix_presentations_created_at'), table_name='presentations')
    op.drop_table('presentations')
    op.drop_index(op.f('ix_post_analytics_post_id'), table_name='post_analytics')
    op.drop_index(op.f('ix_post_analytics_id'), table_name='post_analytics')
    op.drop_table('post_analytics')
    op.drop_index(op.f('ix_landing_pages_user_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_created_at'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_influencer_content_user_id'), table_name='influencer_content')
    op.drop_index(op.f('ix_influencer_content_influencer_id'), table_name='influencer_content')
    op.drop_index(op.f('ix_influencer_content_id'), table_name='influencer_content')
    op.drop_index(op.f('ix_influencer_content_created_at'), table_name='influencer_content')
    op.drop_table('influencer_content')
    op.drop_index(op.f('ix_generated_videos_user_id'), table_name='generated_videos')
    op.drop_index(op.f('ix_generated_videos_id'), table_name='generated_videos')
    op.drop_index(op.f('ix_generated_videos_created_at'), table_name='generated_videos')
    op.drop_table('generated_videos')
    op.drop_index(op.f('ix_generated_logos_user_id'), table_name='generated_logos')
    op.drop_index(op.f('ix_generated_logos_id'), table_name='generated_logos')
    op.drop_index(op.f('ix_generated_logos_created_at'), table_name='generated_logos')
    op.drop_table('generated_logos')
    op.drop_index(op.f('ix_generated_images_user_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_created_at'), table_name='generated_images')
    op.drop_table('generated_images')
    op.drop_index(op.f('ix_generated_audio_user_id'), table_name='generated_audio')
    op.drop_index(op.f('ix_generated_audio_id'), table_name='generated_audio')
    op.drop_index(op.f('ix_generated_audio_created_at'), table_name='generated_audio')
    op.drop_table('generated_audio')
    op.drop_index(op.f('ix_generated_ads_user_id'), table_name='generated_ads')
    op.drop_index(op.f('ix_generated_ads_id'), table_name='generated_ads')
    op.drop_index(op.f('ix_generated_ads_created_at'), table_name='generated_ads')
    op.drop_table('generated_ads')
    op.drop_index(op.f('ix_funnels_user_id'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_id'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_created_at'), table_name='funnels')
    op.drop_table('funnels')
    op.drop_index(op.f('ix_funnel_contacts_id'), table_name='funnel_contacts')
    op.drop_index(op.f('ix_funnel_contacts_funnel_id'), table_name='funnel_contacts')
    op.drop_index(op.f('ix_funnel_contacts_email'), table_name='funnel_contacts')
    op.drop_index(op.f('ix_funnel_contacts_created_at'), table_name='funnel_contacts')
    op.drop_table('funnel_contacts')
    op.drop_index(op.f('ix_funnel_analytics_id'), table_name='funnel_analytics')
    op.drop_index(op.f('ix_funnel_analytics_funnel_id'), table_name='funnel_analytics')
    op.drop_index(op.f('ix_funnel_analytics_date'), table_name='funnel_analytics')
    op.drop_table('funnel_analytics')
    op.drop_index(op.f('ix_email_campaigns_user_id'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_id'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_created_at'), table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_index(op.f('ix_ebooks_user_id'), table_name='ebooks')
    op.drop_index(op.f('ix_ebooks_id'), table_name='ebooks')
    op.drop_index(op.f('ix_ebooks_created_at'), table_name='ebooks')
    op.drop_table('ebooks')
    op.drop_index(op.f('ix_catalog_favorites_user_id'), table_name='catalog_favorites')
    op.drop_index(op.f('ix_catalog_favorites_id'), table_name='catalog_favorites')
    op.drop_table('catalog_favorites')
    op.drop_index(op.f('ix_blog_posts_website_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_created_at'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_ai_influencers_user_id'), table_name='ai_influencers')
    op.drop_index(op.f('ix_ai_influencers_id'), table_name='ai_influencers')
    op.drop_index(op.f('ix_ai_influencers_created_at'), table_name='ai_influencers')
    op.drop_table('ai_influencers')
    # ### end Alembic commands ###
